In [1]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime, date, time, timedelta

In [2]:
path_1='Y://Data//ra//labor//NSDAManagerv1.xlsx'
path_2='Y://Data//ra//labor//NSDAManagerv2.xlsx'
path_3='Y://Data//ra//labor//NSDAManagerv3.xlsx'
path_4='Y://Data//ra//labor//NSDAManagerv4.xlsx'

df_1=pd.read_excel(path_1, skiprows=2)
df_2=pd.read_excel(path_2, skiprows=2)
df_3=pd.read_excel(path_3, skiprows=2)
df_4=pd.read_excel(path_4, skiprows=2)

In [3]:
store1=pd.concat([df_1[df_1['Store Id']==1],df_2[df_2['Store Id']==1],df_3[df_3['Store Id']==1],df_4[df_4['Store Id']==1]],
                 ignore_index=True) #not using original index
store1.drop_duplicates(subset=['Employee Id','Date Skey','Shift End Time','Shift Start Time'],inplace=True)
store1=store1.reset_index(drop=True)
store1

,Division,Store Id,Dept ID,Dept Name,Employee Id,Activity Name,Home Job,Shift End Time,Shift Start Time,Shift Work Duration (Hrs),Date Skey
0,"Raleigh, NC",1.0,FJ,Fine Jewelry,400513,Fine Jewelry (1251),Fine Jewelry Sales,19:30:00,10:30:00,8.00,20150201.0
1,"Raleigh, NC",1.0,FJ,Fine Jewelry,302225,Fine Jewelry (1251),Fine Jewelry Sales,15:59:59.999000,11:00:00,5.00,20150201.0
2,"Raleigh, NC",1.0,MEN,Mens,381994,Men's Combined (1302),Sales - Pay for Performance,16:44:59.999000,10:44:59.999000,6.00,20150201.0
3,"Raleigh, NC",1.0,KID,Kids,115764,Kids Combined (1402),Sales - Pay for Performance,19:15:00,10:44:59.999000,7.50,20150201.0
4,"Raleigh, NC",1.0,KID,Kids,240022,Kids Combined (1402),Sales - Pay for Performance,19:15:00,10:44:59.999000,7.50,20150201.0
5,"Raleigh, NC",1.0,WOM,Womens,391265,Better Sportswear (171),Sales - Pay for Performance,16:15:00,12:59:59.999000,3.25,20150201.0
6,"Raleigh, NC",1.0,WOM,Womens,406544,Better Sportswear (171),Operations Team Associate,19:15:00,10:44:59.999000,7.50,20150201.0
7,"Raleigh, NC",1.0,COS,Cosmetics,360936,Clinique (511),Cosm - Major Lines,19:15:00,11:15:00,7.00,20150201.0
8,"Raleigh, NC",1.0,COS,Cosmetics,387379,Lancome (515),Other Sales,17:00:00,12:00:00,5.00,20150201.0
9,"Raleigh, NC",1.0,COS,Cosmetics,129498,Fine Fragrance 553,Cosm - Pay for Performance,18:30:00,11:29:59.999000,6.00,20150201.0
10,"Raleigh, NC",1.0,SHOE,Shoes,225445,Womens Shoes (611),STM All Other Markets,19:15:00,10:44:59.999000,7.50,20150201.0
11,"Raleigh, NC",1.0,HOME,Home,225841,Home (702),Sales - Pay for Performance,19:15:00,10:44:59.999000,7.50,20150201.0
12,"Raleigh, NC",1.0,HOME,Home,348519,Home (702),Sales - Pay for Performance,17:15:00,12:14:59.999000,5.00,20150201.0
13,"Raleigh, NC",1.0,OPS,Operations Team,228738,MOD/Key Holder,Operations Team Associate,17:00:00,08:00:00,8.00,20150201.0
14,"Raleigh, NC",1.0,FJ,Fine Jewelry,373282,Fine Jewelry (1251),STM Metro A Markets,14:45:00,09:30:00,5.25,20150202.0
15,"Raleigh, NC",1.0,FJ,Fine Jewelry,400513,Fine Jewelry (1251),Fine Jewelry Sales,21:30:00,14:29:59.999000,6.00,20150202.0
16,"Raleigh, NC",1.0,MEN,Mens,116032,Men's Combined (1302),Sales - Pay for Performance,18:14:59.999000,09:45:00,7.50,20150202.0
17,"Raleigh, NC",1.0,MEN,Mens,320125,Men's Combined (1302),Sales - Pay for Performance,15:30:00,09:45:00,5.75,20150202.0
18,"Raleigh, NC",1.0,MEN,Mens,407290,Men's Combined (1302),Sales - Pay for Performance,21:14:59.999000,17:00:00,4.25,20150202.0
19,"Raleigh, NC",1.0,MEN,Mens,407545,Men's Combined (1302),Sales - Commission,21:14:59.999000,15:30:00,5.75,20150202.0
20,"Raleigh, NC",1.0,WOM,Womens,109712,Today's Women (131),Wacoal-Specialist,15:30:00,08:00:00,6.50,20150202.0
21,"Raleigh, NC",1.0,WOM,Womens,361286,Today's Women (131),Sales - Pay for Performance,17:00:00,08:00:00,8.00,20150202.0
22,"Raleigh, NC",1.0,KID,Kids,108403,Kids Combined (1402),Sales - Pay for Performance,21:14:59.999000,15:30:00,5.75,20150202.0
23,"Raleigh, NC",1.0,KID,Kids,343952,Kids Combined (1402),Sales - Pay for Performance,17:00:00,08:00:00,8.00,20150202.0
24,"Raleigh, NC",1.0,KID,Kids,240022,Kids Combined (1402),Sales - Pay for Performance,21:14:59.999000,15:30:00,5.75,20150202.0
25,"Raleigh, NC",1.0,KID,Kids,307214,Kids Combined (1402),Sales - Pay for Performance,15:30:00,09:45:00,5.75,20150202.0
26,"Raleigh, NC",1.0,KID,Kids,386222,Kids Combined (1402),Sales - Pay for Performance,15:30:00,09:45:00,5.75,20150202.0
27,"Raleigh, NC",1.0,WOM,Womens,269796,Better Sportswear (171),Human Resource,16:15:00,08:00:00,7.25,20150202.0
28,"Raleigh, NC",1.0,WOM,Womens,406544,Better Sportswear (171),Operations Team Associate,13:15:00,08:15:00,5.00,20150202.0
29,"Raleigh, NC",1.0,ACC,Accessories,319671,Accessories (241),Sales - Pay for Performance,16:15:00,08:00:00,7.25,20150202.0
...,...,...,...,...,...,...,...,...,...,...,...
11994,"Raleigh, NC",1.0,HOS,HR/Admin,354139,Lead Scheduler (952),Human Resource,13:44:59.999000,07:44:59.999000,6.00,20160129.0
11995,"Raleigh, NC",1.0,HOS,HR/Admin,418773,Lead Scheduler (952),Lead Scheduler,13:30:00,08:29:59.999000,5.00,20160129.0
11996,"Raleigh, NC",1.0,FJ,Fine Jewelry,373282,Fine Jewelry (1251),STM Metro A Markets,18:30:00,09:59:59.999000,7.50,20160130.0
11997,"Raleigh, NC",1.0,FJ,Fine Jewelry,390772,Fine Jewelry (1251),Fine Jewelry Counter Mgr,18:00:00,09:30:00,7.50,20160130.0
11998,"Raleigh, NC",1.0,FJ,Fine Jewelry,422021,Fine Jewelry (1251),Fine Jewelry Sales,21:30:00,13:15:00,7.25,20160130.0
11999,"Raleigh, NC",1.0,FJ,Fine Jewelry,257723,Fine Jewelry (1251),Cosm - Pay for Performance,15:14:59.999000,11:00:00,4.25,20160130.0
12000,"Raleigh, NC",1.0,MEN,Mens,116032,Men's Combined (1302),Sales - Pay for Performance,17:45:00,09:30:00,7.25,20160130.0
12001,"Raleigh, NC",1.0,MEN,Mens,402102,Men's Combined (1302),Other Sales,21:30:00,13:15:00,7.25,20160130.0
12002,"Raleigh, NC",1.0,MEN,Mens,386401,Men's Combined (1302),Sales - Pay for Performance,14:45:00,11:00:00,3.75,20160130.0
12003,"Raleigh, NC",1.0,TRN,Training,407545,Meeting,Sales - Commission,18:00:00,09:00:00,8.00,20160130.0
12004,"Raleigh, NC",1.0,WOM,Womens,361286,Today's Women (131),Sales - Pay for Performance,18:30:00,09:30:00,8.00,20160130.0
12005,"Raleigh, NC",1.0,WOM,Womens,386222,Today's Women (131),Sales - Pay for Performance,21:30:00,12:59:59.999000,7.50,20160130.0
12006,"Raleigh, NC",1.0,KID,Kids,108403,Kids Combined (1402),Sales - Pay for Performance,21:14:59.999000,15:45:00,5.50,20160130.0
12007,"Raleigh, NC",1.0,KID,Kids,307214,Kids Combined (1402),Sales - Pay for Performance,15:45:00,09:30:00,5.75,20160130.0
12008,"Raleigh, NC",1.0,KID,Kids,354859,Kids Combined (1402),Sales - Pay for Performance,21:14:59.999000,15:45:00,5.50,20160130.0
12009,"Raleigh, NC",1.0,KID,Kids,343952,Kids Combined (1402),Sales - Pay for Performance,15:59:59.999000,09:30:00,6.00,20160130.0
12010,"Raleigh, NC",1.0,TRN,Training,225841,Meeting,Sales - Pay for Performance,18:00:00,09:00:00,8.00,20160130.0
12011,"Raleigh, NC",1.0,HOME,Home,348519,Home Combined (1702),Sales - Pay for Performance,14:15:00,11:00:00,3.25,20160130.0
12012,"Raleigh, NC",1.0,WOM,Womens,391265,Better Sportswear (171),Sales - Pay for Performance,18:00:00,09:45:00,7.25,20160130.0
12013,"Raleigh, NC",1.0,ACC,Accessories,262420,Accessories (241),Sales - Pay for Performance,18:30:00,09:30:00,8.00,20160130.0
12014,"Raleigh, NC",1.0,ACC,Accessories,319671,Accessories (241),Sales - Pay for Performance,21:30:00,14:29:59.999000,6.00,20160130.0
12015,"Raleigh, NC",1.0,TRN,Training,419843,Meeting,Sales - Pay for Performance,15:00:00,09:00:00,6.00,20160130.0
12016,"Raleigh, NC",1.0,COS,Cosmetics,360936,Clinique (511),Cosm - Major Lines,21:14:59.999000,12:59:59.999000,7.25,20160130.0
12017,"Raleigh, NC",1.0,COS,Cosmetics,374951,Clinique (511),Cosmetic Counter Manager,17:45:00,09:45:00,7.00,20160130.0
12018,"Raleigh, NC",1.0,COS,Cosmetics,129498,Fine Fragrance 553,Cosm - Pay for Performance,21:14:59.999000,12:59:59.999000,7.25,20160130.0
12019,"Raleigh, NC",1.0,COS,Cosmetics,129984,Fine Fragrance 553,Cosm - Pay for Performance,18:14:59.999000,09:59:59.999000,7.25,20160130.0
12020,"Raleigh, NC",1.0,SHOE,Shoes,406907,Womens Shoes (611),Customer Service,18:00:00,09:30:00,7.50,20160130.0
12021,"Raleigh, NC",1.0,CUST,Office/Cust Serv,387379,Office (943),Other Sales,14:00:00,09:00:00,5.00,20160130.0
12022,"Raleigh, NC",1.0,CUST,Office/Cust Serv,228738,Office (943),Operations Team Associate,17:00:00,08:00:00,8.00,20160130.0
12023,"Raleigh, NC",1.0,HOS,HR/Admin,354139,Lead Scheduler (952),Human Resource,13:44:59.999000,07:44:59.999000,6.00,20160130.0

In [4]:
# Designed Some Preparation Functions 

def getunique(s):
    uni=[]
    for ele in s:
        if ele in uni:
            continue
        else:
            uni.append(ele)
    return uni

def roundT(t):
    if t.second!=59:
        return time(t.hour, t.minute)
    else:
        if t.minute!=59:
            return time(t.hour, t.minute+1)
        else:
            return time((t.hour+1)%24,0) 
        
def timediff(t1,t2):
    hour=(datetime.combine(date.min,t2) - datetime.combine(date.min, t1)).total_seconds()/3600
    if hour>0:
        return hour
    else:
        return 24+hour

def getrest(s, e, intev):
    
    midpoint=datetime.combine(date.min,e)-(datetime.combine(date.min,e)-datetime.combine(date.min,s))/2
    shift=timedelta(0,intev*3600)/2
    rest_start0=midpoint-shift    
    rest_end0  =midpoint+shift
    
    if e>s: # not working to midnight of the second day
        rest_start=time(rest_start0.hour, rest_start0.minute)
        rest_end= time(rest_end0.hour, rest_end0.minute)
        return rest_start, rest_end
        
    else:
        rest_start=time((rest_start0.hour+12)%24, rest_start0.minute)
        rest_end= time((rest_end0.hour+12)%24, rest_end0.minute)
        return rest_start, rest_end

In [5]:
#--------------------------------- Transform the Dataframe Due to some formating issue---------------------------------------

#tranform time
newstart = store1['Shift Start Time'].apply(roundT)
newend   = store1['Shift End Time'].apply(roundT)

store1['Shift End Time']=newend
store1['Shift Start Time']=newstart

# float to string
newdate=[str(int(ele)) for ele in store1['Date Skey']]
store1['Date Skey']=newdate

# store format
newstore=[str(int(ele)) for ele in store1['Store Id']]
store1['Store Id']=newstore

In [6]:
store1

,Division,Store Id,Dept ID,Dept Name,Employee Id,Activity Name,Home Job,Shift End Time,Shift Start Time,Shift Work Duration (Hrs),Date Skey
0,"Raleigh, NC",1,FJ,Fine Jewelry,400513,Fine Jewelry (1251),Fine Jewelry Sales,19:30:00,10:30:00,8.00,20150201
1,"Raleigh, NC",1,FJ,Fine Jewelry,302225,Fine Jewelry (1251),Fine Jewelry Sales,16:00:00,11:00:00,5.00,20150201
2,"Raleigh, NC",1,MEN,Mens,381994,Men's Combined (1302),Sales - Pay for Performance,16:45:00,10:45:00,6.00,20150201
3,"Raleigh, NC",1,KID,Kids,115764,Kids Combined (1402),Sales - Pay for Performance,19:15:00,10:45:00,7.50,20150201
4,"Raleigh, NC",1,KID,Kids,240022,Kids Combined (1402),Sales - Pay for Performance,19:15:00,10:45:00,7.50,20150201
5,"Raleigh, NC",1,WOM,Womens,391265,Better Sportswear (171),Sales - Pay for Performance,16:15:00,13:00:00,3.25,20150201
6,"Raleigh, NC",1,WOM,Womens,406544,Better Sportswear (171),Operations Team Associate,19:15:00,10:45:00,7.50,20150201
7,"Raleigh, NC",1,COS,Cosmetics,360936,Clinique (511),Cosm - Major Lines,19:15:00,11:15:00,7.00,20150201
8,"Raleigh, NC",1,COS,Cosmetics,387379,Lancome (515),Other Sales,17:00:00,12:00:00,5.00,20150201
9,"Raleigh, NC",1,COS,Cosmetics,129498,Fine Fragrance 553,Cosm - Pay for Performance,18:30:00,11:30:00,6.00,20150201
10,"Raleigh, NC",1,SHOE,Shoes,225445,Womens Shoes (611),STM All Other Markets,19:15:00,10:45:00,7.50,20150201
11,"Raleigh, NC",1,HOME,Home,225841,Home (702),Sales - Pay for Performance,19:15:00,10:45:00,7.50,20150201
12,"Raleigh, NC",1,HOME,Home,348519,Home (702),Sales - Pay for Performance,17:15:00,12:15:00,5.00,20150201
13,"Raleigh, NC",1,OPS,Operations Team,228738,MOD/Key Holder,Operations Team Associate,17:00:00,08:00:00,8.00,20150201
14,"Raleigh, NC",1,FJ,Fine Jewelry,373282,Fine Jewelry (1251),STM Metro A Markets,14:45:00,09:30:00,5.25,20150202
15,"Raleigh, NC",1,FJ,Fine Jewelry,400513,Fine Jewelry (1251),Fine Jewelry Sales,21:30:00,14:30:00,6.00,20150202
16,"Raleigh, NC",1,MEN,Mens,116032,Men's Combined (1302),Sales - Pay for Performance,18:15:00,09:45:00,7.50,20150202
17,"Raleigh, NC",1,MEN,Mens,320125,Men's Combined (1302),Sales - Pay for Performance,15:30:00,09:45:00,5.75,20150202
18,"Raleigh, NC",1,MEN,Mens,407290,Men's Combined (1302),Sales - Pay for Performance,21:15:00,17:00:00,4.25,20150202
19,"Raleigh, NC",1,MEN,Mens,407545,Men's Combined (1302),Sales - Commission,21:15:00,15:30:00,5.75,20150202
20,"Raleigh, NC",1,WOM,Womens,109712,Today's Women (131),Wacoal-Specialist,15:30:00,08:00:00,6.50,20150202
21,"Raleigh, NC",1,WOM,Womens,361286,Today's Women (131),Sales - Pay for Performance,17:00:00,08:00:00,8.00,20150202
22,"Raleigh, NC",1,KID,Kids,108403,Kids Combined (1402),Sales - Pay for Performance,21:15:00,15:30:00,5.75,20150202
23,"Raleigh, NC",1,KID,Kids,343952,Kids Combined (1402),Sales - Pay for Performance,17:00:00,08:00:00,8.00,20150202
24,"Raleigh, NC",1,KID,Kids,240022,Kids Combined (1402),Sales - Pay for Performance,21:15:00,15:30:00,5.75,20150202
25,"Raleigh, NC",1,KID,Kids,307214,Kids Combined (1402),Sales - Pay for Performance,15:30:00,09:45:00,5.75,20150202
26,"Raleigh, NC",1,KID,Kids,386222,Kids Combined (1402),Sales - Pay for Performance,15:30:00,09:45:00,5.75,20150202
27,"Raleigh, NC",1,WOM,Womens,269796,Better Sportswear (171),Human Resource,16:15:00,08:00:00,7.25,20150202
28,"Raleigh, NC",1,WOM,Womens,406544,Better Sportswear (171),Operations Team Associate,13:15:00,08:15:00,5.00,20150202
29,"Raleigh, NC",1,ACC,Accessories,319671,Accessories (241),Sales - Pay for Performance,16:15:00,08:00:00,7.25,20150202
...,...,...,...,...,...,...,...,...,...,...,...
11994,"Raleigh, NC",1,HOS,HR/Admin,354139,Lead Scheduler (952),Human Resource,13:45:00,07:45:00,6.00,20160129
11995,"Raleigh, NC",1,HOS,HR/Admin,418773,Lead Scheduler (952),Lead Scheduler,13:30:00,08:30:00,5.00,20160129
11996,"Raleigh, NC",1,FJ,Fine Jewelry,373282,Fine Jewelry (1251),STM Metro A Markets,18:30:00,10:00:00,7.50,20160130
11997,"Raleigh, NC",1,FJ,Fine Jewelry,390772,Fine Jewelry (1251),Fine Jewelry Counter Mgr,18:00:00,09:30:00,7.50,20160130
11998,"Raleigh, NC",1,FJ,Fine Jewelry,422021,Fine Jewelry (1251),Fine Jewelry Sales,21:30:00,13:15:00,7.25,20160130
11999,"Raleigh, NC",1,FJ,Fine Jewelry,257723,Fine Jewelry (1251),Cosm - Pay for Performance,15:15:00,11:00:00,4.25,20160130
12000,"Raleigh, NC",1,MEN,Mens,116032,Men's Combined (1302),Sales - Pay for Performance,17:45:00,09:30:00,7.25,20160130
12001,"Raleigh, NC",1,MEN,Mens,402102,Men's Combined (1302),Other Sales,21:30:00,13:15:00,7.25,20160130
12002,"Raleigh, NC",1,MEN,Mens,386401,Men's Combined (1302),Sales - Pay for Performance,14:45:00,11:00:00,3.75,20160130
12003,"Raleigh, NC",1,TRN,Training,407545,Meeting,Sales - Commission,18:00:00,09:00:00,8.00,20160130
12004,"Raleigh, NC",1,WOM,Womens,361286,Today's Women (131),Sales - Pay for Performance,18:30:00,09:30:00,8.00,20160130
12005,"Raleigh, NC",1,WOM,Womens,386222,Today's Women (131),Sales - Pay for Performance,21:30:00,13:00:00,7.50,20160130
12006,"Raleigh, NC",1,KID,Kids,108403,Kids Combined (1402),Sales - Pay for Performance,21:15:00,15:45:00,5.50,20160130
12007,"Raleigh, NC",1,KID,Kids,307214,Kids Combined (1402),Sales - Pay for Performance,15:45:00,09:30:00,5.75,20160130
12008,"Raleigh, NC",1,KID,Kids,354859,Kids Combined (1402),Sales - Pay for Performance,21:15:00,15:45:00,5.50,20160130
12009,"Raleigh, NC",1,KID,Kids,343952,Kids Combined (1402),Sales - Pay for Performance,16:00:00,09:30:00,6.00,20160130
12010,"Raleigh, NC",1,TRN,Training,225841,Meeting,Sales - Pay for Performance,18:00:00,09:00:00,8.00,20160130
12011,"Raleigh, NC",1,HOME,Home,348519,Home Combined (1702),Sales - Pay for Performance,14:15:00,11:00:00,3.25,20160130
12012,"Raleigh, NC",1,WOM,Womens,391265,Better Sportswear (171),Sales - Pay for Performance,18:00:00,09:45:00,7.25,20160130
12013,"Raleigh, NC",1,ACC,Accessories,262420,Accessories (241),Sales - Pay for Performance,18:30:00,09:30:00,8.00,20160130
12014,"Raleigh, NC",1,ACC,Accessories,319671,Accessories (241),Sales - Pay for Performance,21:30:00,14:30:00,6.00,20160130
12015,"Raleigh, NC",1,TRN,Training,419843,Meeting,Sales - Pay for Performance,15:00:00,09:00:00,6.00,20160130
12016,"Raleigh, NC",1,COS,Cosmetics,360936,Clinique (511),Cosm - Major Lines,21:15:00,13:00:00,7.25,20160130
12017,"Raleigh, NC",1,COS,Cosmetics,374951,Clinique (511),Cosmetic Counter Manager,17:45:00,09:45:00,7.00,20160130
12018,"Raleigh, NC",1,COS,Cosmetics,129498,Fine Fragrance 553,Cosm - Pay for Performance,21:15:00,13:00:00,7.25,20160130
12019,"Raleigh, NC",1,COS,Cosmetics,129984,Fine Fragrance 553,Cosm - Pay for Performance,18:15:00,10:00:00,7.25,20160130
12020,"Raleigh, NC",1,SHOE,Shoes,406907,Womens Shoes (611),Customer Service,18:00:00,09:30:00,7.50,20160130
12021,"Raleigh, NC",1,CUST,Office/Cust Serv,387379,Office (943),Other Sales,14:00:00,09:00:00,5.00,20160130
12022,"Raleigh, NC",1,CUST,Office/Cust Serv,228738,Office (943),Operations Team Associate,17:00:00,08:00:00,8.00,20160130
12023,"Raleigh, NC",1,HOS,HR/Admin,354139,Lead Scheduler (952),Human Resource,13:45:00,07:45:00,6.00,20160130

In [7]:
#------------------------------------------- Some Simple Stats----------------------------------------------------
# total date : 362
len(set(store1['Date Skey']))

# total employee : 151
len(set(store1['Employee Id']))

# number of departments : 14
len(set(store1['Dept ID']))

14

In [7]:
#---------------------------------------------- Hourly Level Analysis ------------------------------------------------------- 
#initialize null dataframe
datelist=getunique(store1['Date Skey'])
hourname=[ele for ele in range(24)]
target_df=pd.DataFrame(columns=['date']+hourname)
index=0

for d in datelist:
    target_df.loc[index,['date']]=d
    index+=1
    
target_df.fillna(0, inplace=True)    



index=0
for d in datelist:
    
    subdf=store1[store1['Date Skey']==d]
    subindex=subdf.index
        
    for i in subindex:
        start = subdf['Shift Start Time'][i]
        end   = subdf['Shift End Time'][i]
        duration=subdf['Shift Work Duration (Hrs)'][i]
        inteval=timediff(start,end)-duration                
        rest_s, rest_e=getrest(start, end, inteval)        
 
        #take care of the first hour
        target_df.loc[index,[start.hour]]=target_df[start.hour][index]+(60-start.minute)/60
        
        #working hours before break
        if rest_s.hour>start.hour:
            for x in range(start.hour+1, rest_s.hour):
                #print(x)
                target_df.loc[index,[x]]=target_df[x][index]+1
            #count the rest start hour
            target_df.loc[index,[rest_s.hour]]=target_df[rest_s.hour][index]+(rest_s.minute)/60
        else: #already the other day
            for x in range(start.hour+1, 24):
                target_df.loc[index,[x]]=target_df[x][index]+1
            for x in range(0, rest_s.hour):
                target_df.loc[index+1,[x]]=target_df[x][index+1]+1
            target_df.loc[index+1,[rest_s.hour]]=target_df[rest_s.hour][index+1]+(rest_s.minute)/60
            
        #woring hours after break
        if end>start: #must in the same day
            #count first hour after break
            target_df.loc[index,[rest_e.hour]]=target_df[rest_e.hour][index]+(60-rest_e.minute)/60
            
            for x in range(rest_e.hour+1, end.hour):
                target_df.loc[index,[x]]=target_df[x][index]+1
            #count the last hour
            target_df.loc[index,[end.hour]]=target_df[end.hour][index]+(end.minute)/60
            
        else:
            if end>rest_e: #period after break tatally in the second day
                target_df.loc[index+1,[rest_e.hour]]=target_df[rest_e.hour][index+1]+(60-rest_e.minute)/60
                for x in range(rest_e.hour+1, end.hour):
                    target_df.loc[index+1,[x]]=target_df[x][index+1]+1
                
            else: #rest end hour in the first day, end hour in the second day
                target_df.loc[index,[rest_e.hour]]=target_df[rest_e.hour][index]+(60-rest_e.minute)/60
                
                for x in range(rest_e.hour+1, 24):
                    target_df.loc[index,[x]]=target_df[x][index]+1
                    
                for x in range(0, end.hour):
                    target_df.loc[index+1,[x]]=target_df[x][index+1]+1                   
            
            #count the last hour            
            target_df.loc[index+1,[end.hour]]=target_df[end.hour][index+1]+(end.minute)/60
                                            
        
    index+=1

print("Finished, ALL Good")

Finished, ALL Good

In [9]:
target_df

,date,0,1,2,3,4,5,6,7,8,...,14,15,16,17,18,19,20,21,22,23
0,20150201,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,1.00,...,10.250000,9.750000,12.000000,8.250000,7.500000,2.00,0.00,0.00,0.0,0.0
1,20150202,0.0,0.0,0.0,0.0,0.0,4.0,4.00,8.25,17.25,...,20.883333,21.750000,14.500000,10.250000,9.500000,8.00,8.00,2.25,0.0,0.0
2,20150203,0.0,0.0,0.0,0.0,0.0,3.0,3.00,6.25,10.75,...,19.283333,22.250000,17.866667,15.633333,13.500000,11.00,11.00,3.25,0.0,0.0
3,20150204,0.0,0.0,0.0,0.0,0.0,4.0,4.00,7.25,9.75,...,16.766667,15.000000,9.250000,8.250000,7.250000,6.25,6.00,1.75,0.0,0.0
4,20150205,0.0,0.0,0.0,0.0,0.0,4.0,4.00,7.00,9.75,...,13.266667,13.500000,12.000000,10.750000,10.250000,10.00,10.00,2.50,0.0,0.0
5,20150206,0.0,0.0,0.0,0.0,0.0,4.0,4.00,7.00,10.00,...,18.383333,22.500000,23.116667,17.633333,17.500000,16.50,15.00,6.00,0.0,0.0
6,20150207,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,1.50,...,22.633333,26.250000,24.483333,19.516667,20.750000,12.00,10.00,3.75,0.0,0.0
7,20150208,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,14.766667,14.366667,17.883333,15.000000,14.000000,3.75,0.00,0.00,0.0,0.0
8,20150209,0.0,0.0,0.0,0.0,0.0,4.0,6.00,8.25,10.50,...,18.150000,16.750000,13.116667,11.883333,10.750000,10.00,10.00,2.50,0.0,0.0
9,20150210,0.0,0.0,0.0,0.0,0.0,4.0,6.00,7.25,10.00,...,17.400000,18.000000,15.366667,13.383333,11.000000,10.00,10.00,2.75,0.0,0.0
10,20150211,0.0,0.0,0.0,0.0,0.0,0.0,4.00,5.25,8.00,...,15.016667,15.500000,15.116667,12.633333,7.000000,7.00,7.00,1.75,0.0,0.0
11,20150212,0.0,0.0,0.0,0.0,0.0,4.0,6.00,7.00,8.00,...,16.633333,14.250000,13.366667,14.633333,13.250000,13.00,12.25,3.50,0.0,0.0
12,20150213,0.0,0.0,0.0,0.0,0.0,4.0,6.00,7.25,9.50,...,17.633333,21.250000,18.233333,18.266667,16.000000,12.00,11.00,3.75,0.0,0.0
13,20150214,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,1.00,...,25.050000,30.000000,28.866667,23.633333,21.750000,15.75,12.50,4.75,0.0,0.0
14,20150215,0.0,0.0,0.0,0.0,0.0,4.0,4.00,4.00,4.00,...,14.500000,15.500000,17.500000,13.750000,9.500000,2.00,0.00,0.00,0.0,0.0
15,20150216,0.0,0.0,0.0,0.0,0.0,4.0,6.00,8.25,11.00,...,19.016667,17.500000,14.500000,11.750000,10.750000,10.00,10.00,2.25,0.0,0.0
16,20150217,0.0,0.0,0.0,0.0,0.0,0.0,2.00,2.25,4.75,...,15.400000,15.250000,14.250000,10.750000,10.000000,10.00,10.00,3.00,0.0,0.0
17,20150218,0.0,0.0,0.0,0.0,0.0,4.0,6.00,7.25,9.50,...,18.516667,17.383333,13.616667,12.383333,9.250000,9.00,9.00,2.50,0.0,0.0
18,20150219,0.0,0.0,0.0,0.0,0.0,4.0,6.00,7.00,8.50,...,13.000000,11.633333,10.116667,11.133333,8.750000,7.00,7.00,2.25,0.0,0.0
19,20150220,0.0,0.0,0.0,0.0,0.0,4.0,6.00,7.25,9.00,...,17.766667,22.750000,20.616667,20.383333,16.250000,12.00,12.00,5.00,0.0,0.0
20,20150221,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,1.50,...,24.016667,31.133333,27.366667,19.133333,17.250000,11.50,11.00,4.50,0.0,0.0
21,20150222,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,15.366667,16.133333,18.750000,15.750000,12.250000,2.75,0.00,0.00,0.0,0.0
22,20150223,0.0,0.0,0.0,0.0,0.0,0.0,2.00,7.25,11.50,...,15.900000,14.883333,13.750000,11.366667,9.883333,9.00,9.00,2.50,0.0,0.0
23,20150224,0.0,0.0,0.0,0.0,0.0,3.5,7.00,8.25,10.50,...,14.400000,17.500000,16.000000,13.750000,12.000000,8.75,8.00,2.25,0.0,0.0
24,20150225,0.0,0.0,0.0,0.0,0.0,0.0,2.00,6.25,9.50,...,17.766667,15.250000,15.616667,13.133333,9.250000,8.75,6.75,1.75,0.0,0.0
25,20150226,0.0,0.0,0.0,0.0,0.0,0.0,1.00,6.00,7.00,...,17.633333,18.250000,16.000000,13.733333,12.766667,11.00,10.00,3.00,0.0,0.0
26,20150227,0.0,0.0,0.0,0.0,0.0,3.5,7.00,8.25,11.50,...,15.766667,19.250000,15.733333,18.266667,16.000000,15.00,14.25,5.50,0.0,0.0
27,20150228,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,1.50,...,19.650000,27.633333,27.983333,21.766667,20.000000,10.25,8.00,3.25,0.0,0.0
28,20150301,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,1.00,...,10.116667,9.133333,10.750000,8.250000,7.250000,1.75,0.00,0.00,0.0,0.0
29,20150302,0.0,0.0,0.0,0.0,0.0,3.5,7.00,9.25,18.00,...,17.116667,15.883333,15.500000,11.366667,12.383333,9.25,9.00,2.25,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,20160101,0.0,0.0,0.0,0.0,0.0,0.0,7.00,9.25,13.00,...,20.150000,21.500000,21.000000,17.000000,11.750000,4.25,2.00,0.50,0.0,0.0
333,20160102,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,1.00,...,23.516667,27.500000,23.483333,17.516667,11.750000,10.00,10.00,3.75,0.0,0.0
334,20160103,0.0,0.0,0.0,0.0,0.0,4.0,4.00,5.00,5.00,...,11.116667,10.500000,13.633333,11.250000,10.000000,2.75,0.00,0.00,0.0,0.0
335,20160104,0.0,0.0,0.0,0.0,0.0,3.0,8.00,11.25,11.00,...,13.133333,14.500000,15.366667,10.883333,10.500000,9.00,7.50,2.00,0.0,0.0
336,20160105,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.25,4.50,...,15.133333,17.750000,16.250000,13.000000,13.000000,9.00,9.00,2.75,0.0,0.0
337,20160106,0.0,0.0,0.0,0.0,0.0,4.0,8.00,12.25,11.50,...,13.750000,15.633333,13.750000,11.750000,11.000000,9.00,9.00,2.00,0.0,0.0
338,20160107,0.0,0.0,0.0,0.0,0.0,4.0,8.00,11.00,10.00,...,12.000000,16.000000,12.500000,11.116667,10.883333,7.00,7.00,2.25,0.0,0.0
339,20160108,0.0,0.0,0.0,0.0,0.0,0.0,3.00,4.25,7.50,...,14.766667,16.750000,16.366667,14.133333,13.000000,9.75,9.00,3.25,0.0,0.0
340,20160109,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,1.00,...,17.383333,19.000000,17.366667,12.383333,13.500000,13.00,13.00,5.00,0.0,0.0
341,20160110,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,...,12.733333,13.766667,15.750000,13.750000,13.000000,4.50,0.00,0.00,0.0,0.0
342,20160111,0.0,0.0,0.0,0.0,0.0,4.0,6.00,9.75,11.00,...,19.250000,17.500000,14.366667,9.133333,12.250000,11.00,9.00,2.75,0.0,0.0
343,20160112,0.0,0.0,0.0,0.0,0.0,4.0,6.00,8.75,9.50,...,12.250000,15.000000,13.750000,10.500000,10.500000,9.00,9.00,3.50,0.0,0.0
344,20160113,0.0,0.0,0.0,0.0,0.0,4.0,7.00,8.75,9.00,...,12.250000,14.633333,12.250000,12.000000,13.250000,9.00,7.25,2.75,0.0,0.0
345,20160114,0.0,0.0,0.0,0.0,0.0,0.0,4.00,5.00,8.50,...,12.883333,16.250000,13.000000,10.616667,12.133333,9.00,8.00,3.75,0.0,0.0
346,20160115,0.0,0.0,0.0,0.0,0.0,4.0,6.00,9.25,9.50,...,16.000000,14.250000,13.250000,14.000000,15.000000,14.00,12.50,5.75,0.0,0.0
347,20160116,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,3.00,...,18.000000,19.000000,17.366667,14.133333,11.500000,9.00,9.00,3.25,0.0,0.0
348,20160117,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.50,...,11.366667,9.883333,10.750000,11.000000,11.000000,4.50,2.00,2.00,2.0,2.0
349,20160118,2.0,2.0,2.0,2.0,2.0,6.5,8.00,10.25,14.00,...,13.500000,17.250000,13.366667,11.383333,10.000000,7.00,7.00,2.25,0.0,0.0
350,20160119,0.0,0.0,0.0,0.0,0.0,0.0,0.00,4.25,9.50,...,16.250000,16.000000,11.000000,9.500000,9.000000,7.00,7.00,2.00,0.0,0.0
351,20160120,0.0,0.0,0.0,0.0,0.0,4.0,5.00,7.25,10.50,...,14.133333,16.000000,13.000000,12.116667,12.633333,9.00,9.00,2.25,0.0,0.0
352,20160121,0.0,0.0,0.0,0.0,0.0,0.0,3.00,5.50,17.50,...,11.250000,13.000000,11.733333,11.266667,10.500000,8.00,8.00,2.50,0.0,0.0
353,20160122,0.0,0.0,0.0,0.0,0.0,20.5,23.00,24.25,30.00,...,11.500000,12.366667,12.750000,10.483333,14.650000,13.00,12.25,4.25,0.0,0.0
354,20160123,0.0,0.0,0.0,0.0,0.0,31.0,32.75,33.25,34.00,...,12.250000,15.750000,14.116667,11.000000,13.133333,10.00,10.00,3.50,0.0,0.0
355,20160124,0.0,0.0,0.0,0.0,0.0,27.0,28.00,28.00,28.00,...,13.116667,14.500000,14.133333,13.250000,11.750000,2.50,0.00,0.00,0.0,0.0
356,20160125,0.0,0.0,0.0,0.0,0.0,5.0,7.00,9.75,10.00,...,14.516667,15.250000,11.250000,8.983333,7.516667,7.00,7.00,1.50,0.0,0.0
357,20160126,0.0,0.0,0.0,0.0,0.0,4.0,9.00,11.75,12.00,...,13.766667,18.250000,15.500000,14.250000,11.750000,8.25,7.50,2.00,0.0,0.0
358,20160127,0.0,0.0,0.0,0.0,0.0,0.0,0.00,4.25,6.50,...,11.133333,13.000000,9.616667,7.000000,10.383333,8.00,8.00,2.25,0.0,0.0
359,20160128,0.0,0.0,0.0,0.0,0.0,4.0,8.00,10.00,11.50,...,16.383333,17.250000,14.616667,13.383333,15.500000,10.25,10.00,2.75,0.0,0.0
360,20160129,0.0,0.0,0.0,0.0,0.0,0.0,3.00,5.25,9.50,...,17.500000,19.383333,16.500000,16.000000,16.250000,9.50,9.00,3.75,0.0,0.0
361,20160130,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.25,2.00,...,18.900000,20.500000,18.716667,14.283333,9.250000,8.00,8.00,3.00,0.0,0.0

In [20]:
#reshape the dataframe and sort by date & hour
trydf=pd.melt(target_df, id_vars=["date"])
trydf=trydf.rename(columns={'variable': 'hour'})
trydf=trydf.sort(columns=['date','hour'])
trydf=trydf.reset_index(drop=True)
trydf

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

          date hour      value
0     20150201    0   0.000000
1     20150201    1   0.000000
2     20150201    2   0.000000
3     20150201    3   0.000000
4     20150201    4   0.000000
5     20150201    5   0.000000
6     20150201    6   0.000000
7     20150201    7   0.000000
8     20150201    8   1.000000
9     20150201    9   1.000000
10    20150201   10   3.000000
11    20150201   11  10.250000
12    20150201   12  11.750000
13    20150201   13  14.000000
14    20150201   14  10.250000
15    20150201   15   9.750000
16    20150201   16  12.000000
17    20150201   17   8.250000
18    20150201   18   7.500000
19    20150201   19   2.000000
20    20150201   20   0.000000
21    20150201   21   0.000000
22    20150201   22   0.000000
23    20150201   23   0.000000
24    20150202    0   0.000000
25    20150202    1   0.000000
26    20150202    2   0.000000
27    20150202    3   0.000000
28    20150202    4   0.000000
29    20150202    5   4.000000
...        ...  ...        ...
8658  20160129   18  16.250000
8659  20160129   19   9.500000
8660  20160129   20   9.000000
8661  20160129   21   3.750000
8662  20160129   22   0.000000
8663  20160129   23   0.000000
8664  20160130    0   0.000000
8665  20160130    1   0.000000
8666  20160130    2   0.000000
8667  20160130    3   0.000000
8668  20160130    4   0.000000
8669  20160130    5   0.000000
8670  20160130    6   0.000000
8671  20160130    7   0.250000
8672  20160130    8   2.000000
8673  20160130    9  10.000000
8674  20160130   10  17.000000
8675  20160130   11  20.000000
8676  20160130   12  18.000000
8677  20160130   13  16.850000
8678  20160130   14  18.900000
8679  20160130   15  20.500000
8680  20160130   16  18.716667
8681  20160130   17  14.283333
8682  20160130   18   9.250000
8683  20160130   19   8.000000
8684  20160130   20   8.000000
8685  20160130   21   3.000000
8686  20160130   22   0.000000
8687  20160130   23   0.000000

[8688 rows x 3 columns]

In [21]:
# save dataframe temporally
trydf.to_pickle("Y://Data//ra//MangHour.pkl")

In [ ]:
#----------------------------------------------   Person Level Analysis  -------------------------------------------------------

In [8]:
datelist=getunique(store1['Date Skey'])

plevel_df=pd.DataFrame(columns=['date','emp_id','sys_duration'])

ini_index=0

#For those irregular records: night shift(and have no shift the second day), put them at the end of the dataframe first.
bottomindex=100000
#Initilize all 0
for d in store1['Date Skey']:
    plevel_df.loc[ini_index,['date']]=d
    ini_index+=1
plevel_df.fillna(0, inplace=True)  

for i in store1.index:
    empid = store1['Employee Id'][i]
    date_1  = store1['Date Skey'][i]
    start = store1['Shift Start Time'][i]
    end   = store1['Shift End Time'][i]
    
    allinteval=timediff(start,end)   
    intbefore =timediff(start,time(0,0)) 
    intafter  =timediff(time(0,0),end)
    plevel_df.loc[i,['emp_id']]=empid
    if end>start:  #most case , i.e. in the same day
        plevel_df.loc[i,['sys_duration']]= plevel_df['sys_duration'][i]+allinteval
        
    else:    
        #take care of today's
        plevel_df.loc[i,['sys_duration']]= plevel_df['sys_duration'][i]+intbefore

        nextshiftday=datelist[datelist.index(date_1)+1]
        
        t=datetime.strptime(date_1,'%Y%m%d')
        nextdate=(date(t.year,t.month,t.day)+timedelta(1)).strftime('%Y%m%d')

        subdf  =store1[store1['Date Skey']==nextdate]
        if empid in subdf['Employee Id'].tolist(): #find the next position
            a=subdf[subdf['Employee Id']==empid].index.tolist()[0]
            plevel_df.loc[a,['sys_duration']]= plevel_df['sys_duration'][a]+intafter
        else:
            if end==time(0,0):
                continue
            else:
                #insert those rows at the very bottom
                plevel_df.loc[bottomindex,:]=[nextdate,empid,intafter]
                print('irregular',date_1, nextdate, nextshiftday,start,end)
                bottomindex+=1
    
# In this measure, there's a guy working on Chrismas: error 20151224 20151225 20151226 17:00:00 00:30:00

irregular 20150828 20150829 20150829 17:00:00 02:00:00
irregular 20151019 20151020 20151020 21:00:00 05:00:00
irregular 20151126 20151127 20151127 17:30:00 06:00:00
irregular 20151126 20151127 20151127 17:30:00 05:30:00
irregular 20151126 20151127 20151127 19:00:00 06:00:00
irregular 20151126 20151127 20151127 20:00:00 08:00:00
irregular 20151126 20151127 20151127 18:00:00 06:00:00
irregular 20151126 20151127 20151127 19:00:00 07:00:00
irregular 20151126 20151127 20151127 20:00:00 06:00:00
irregular 20151126 20151127 20151127 18:00:00 06:00:00
irregular 20151224 20151225 20151226 17:00:00 00:30:00

In [9]:
plevel_df

            date  emp_id  sys_duration
0       20150201  400513          9.00
1       20150201  302225          5.00
2       20150201  381994          6.00
3       20150201  115764          8.50
4       20150201  240022          8.50
5       20150201  391265          3.25
6       20150201  406544          8.50
7       20150201  360936          8.00
8       20150201  387379          5.00
9       20150201  129498          7.00
10      20150201  225445          8.50
11      20150201  225841          8.50
12      20150201  348519          5.00
13      20150201  228738          9.00
14      20150202  373282          5.25
15      20150202  400513          7.00
16      20150202  116032          8.50
17      20150202  320125          5.75
18      20150202  407290          4.25
19      20150202  407545          5.75
20      20150202  109712          7.50
21      20150202  361286          9.00
22      20150202  108403          5.75
23      20150202  343952          9.00
24      20150202  240022          5.75
25      20150202  307214          5.75
26      20150202  386222          5.75
27      20150202  269796          8.25
28      20150202  406544          5.00
29      20150202  319671          8.25
...          ...     ...           ...
12005   20160130  386222          8.50
12006   20160130  108403          5.50
12007   20160130  307214          6.25
12008   20160130  354859          5.50
12009   20160130  343952          6.50
12010   20160130  225841          9.00
12011   20160130  348519          3.25
12012   20160130  391265          8.25
12013   20160130  262420          9.00
12014   20160130  319671          7.00
12015   20160130  419843          6.00
12016   20160130  360936          8.25
12017   20160130  374951          8.00
12018   20160130  129498          8.25
12019   20160130  129984          8.25
12020   20160130  406907          8.50
12021   20160130  387379          5.00
12022   20160130  228738          9.00
12023   20160130  354139          6.00
100000  20150829  350285          2.00
100001  20151020  406544          5.00
100002  20151127  111533          6.00
100003  20151127  392566          5.50
100004  20151127  359858          6.00
100005  20151127  257050          8.00
100006  20151127  240598          6.00
100007  20151127  350285          7.00
100008  20151127  415258          6.00
100009  20151127  406544          6.00
100010  20151225  243703          0.50

[12035 rows x 3 columns]

In [49]:
sub1=store1[store1['Date Skey']=='20160130']

sub2=sub1[sub1['Employee Id']==225841]
sub2

,Division,Store Id,Dept ID,Dept Name,Employee Id,Activity Name,Home Job,Shift End Time,Shift Start Time,Shift Work Duration (Hrs),Date Skey
12740,"Raleigh, NC",1,TRN,Training,225841,Meeting,Sales - Pay for Performance,18:00:00,09:00:00,8.0,20160130
12741,"Raleigh, NC",1,HOME,Home,225841,Home Combined (1702),Sales - Pay for Performance,18:00:00,09:00:00,8.0,20160130

In [10]:
plevel_df=plevel_df.reset_index(drop=True).sort(columns=['date']).reset_index(drop=True)

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [11]:
plevel_df

           date  emp_id  sys_duration
0      20150201  400513          9.00
1      20150201  228738          9.00
2      20150201  348519          5.00
3      20150201  225841          8.50
4      20150201  129498          7.00
5      20150201  387379          5.00
6      20150201  360936          8.00
7      20150201  225445          8.50
8      20150201  391265          3.25
9      20150201  240022          8.50
10     20150201  115764          8.50
11     20150201  381994          6.00
12     20150201  302225          5.00
13     20150201  406544          8.50
14     20150202  257050          9.00
15     20150202  393862          9.00
16     20150202  354960          5.50
17     20150202  119047          3.25
18     20150202  225841          5.00
19     20150202  240598          9.00
20     20150202  350285          9.00
21     20150202  354139          9.00
22     20150202  359858          5.00
23     20150202  330830          9.00
24     20150202  351802          9.00
25     20150202  407518          8.00
26     20150202  228738          9.00
27     20150202  129984          3.25
28     20150202  386692          9.00
29     20150202  392566          6.00
...         ...     ...           ...
12005  20160129  109650          8.00
12006  20160129  319671          6.50
12007  20160130  360936          8.25
12008  20160130  354139          6.00
12009  20160130  228738          9.00
12010  20160130  387379          5.00
12011  20160130  406907          8.50
12012  20160130  129984          8.25
12013  20160130  129498          8.25
12014  20160130  374951          8.00
12015  20160130  373282          8.50
12016  20160130  419843          6.00
12017  20160130  262420          9.00
12018  20160130  390772          8.50
12019  20160130  422021          8.25
12020  20160130  257723          4.25
12021  20160130  116032          8.25
12022  20160130  402102          8.25
12023  20160130  386401          3.75
12024  20160130  407545          9.00
12025  20160130  361286          9.00
12026  20160130  386222          8.50
12027  20160130  108403          5.50
12028  20160130  307214          6.25
12029  20160130  343952          6.50
12030  20160130  225841          9.00
12031  20160130  348519          3.25
12032  20160130  391265          8.25
12033  20160130  319671          7.00
12034  20160130  354859          5.50

[12035 rows x 3 columns]

In [18]:
plevel_df.to_pickle("Y://Data//ra//MangPerson.pkl")